### PR TITLE
Smoother histogram output, plus add examples/graph taken from readme

### PR DESCRIPTION
**Pull request by japhb**
Still passes tests; I tried to maintain your code style (with the exception of a couple whitespace fixes my editor supplied).

### CODE REVIEW

**Comment by bbkr** [comment]
Thanks!

Was https://rosettacode.org/wiki/Statistics/Normal_distribution#Raku your code as well? It uses the same concept.

**Comment by bbkr** [comment]
I've renamed examples/graph to examples/graph.raku according to https://github.com/Raku/problem-solving/issues/106 guidelines.

**Comment by bbkr** [comment]
Also updated README in https://github.com/bbkr/Metropolis/commit/2411be7d386d029b05f12f908b0d4d7493145a94 .

**Comment by japhb** [comment]
> Was https://rosettacode.org/wiki/Statistics/Normal_distribution#Raku your code as well? It uses the same concept.

Nope, not I.  :-)

I just use it a lot for stuff like https://github.com/japhb/Terminal-QuickCharts .

**Pull request merged**
